//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 summerlmm.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildAlertSpec) DeepCopyInto(out *ChildAlertSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildAlertSpec.
func (in *ChildAlertSpec) DeepCopy() *ChildAlertSpec {
	if in == nil {
		return nil
	}
	out := new(ChildAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildClusterState) DeepCopyInto(out *ChildClusterState) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildClusterState.
func (in *ChildClusterState) DeepCopy() *ChildClusterState {
	if in == nil {
		return nil
	}
	out := new(ChildClusterState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRegisterSpec) DeepCopyInto(out *NetworkRegisterSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRegisterSpec.
func (in *NetworkRegisterSpec) DeepCopy() *NetworkRegisterSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkRegisterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQpsIncreaseOrDecreaseSpec) DeepCopyInto(out *PodQpsIncreaseOrDecreaseSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQpsIncreaseOrDecreaseSpec.
func (in *PodQpsIncreaseOrDecreaseSpec) DeepCopy() *PodQpsIncreaseOrDecreaseSpec {
	if in == nil {
		return nil
	}
	out := new(PodQpsIncreaseOrDecreaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQpsQuotaRealSpec) DeepCopyInto(out *PodQpsQuotaRealSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQpsQuotaRealSpec.
func (in *PodQpsQuotaRealSpec) DeepCopy() *PodQpsQuotaRealSpec {
	if in == nil {
		return nil
	}
	out := new(PodQpsQuotaRealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQpsQuotaSpec) DeepCopyInto(out *PodQpsQuotaSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQpsQuotaSpec.
func (in *PodQpsQuotaSpec) DeepCopy() *PodQpsQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(PodQpsQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Quota) DeepCopyInto(out *Quota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Status = in.Status
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Quota.
func (in *Quota) DeepCopy() *Quota {
	if in == nil {
		return nil
	}
	out := new(Quota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Quota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaList) DeepCopyInto(out *QuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Quota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaList.
func (in *QuotaList) DeepCopy() *QuotaList {
	if in == nil {
		return nil
	}
	out := new(QuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaSpec) DeepCopyInto(out *QuotaSpec) {
	*out = *in
	if in.NetworkRegister != nil {
		in, out := &in.NetworkRegister, &out.NetworkRegister
		*out = make([]NetworkRegisterSpec, len(*in))
		copy(*out, *in)
	}
	if in.ChildName != nil {
		in, out := &in.ChildName, &out.ChildName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ChildAlert != nil {
		in, out := &in.ChildAlert, &out.ChildAlert
		*out = make([]ChildAlertSpec, len(*in))
		copy(*out, *in)
	}
	if in.PodQpsQuota != nil {
		in, out := &in.PodQpsQuota, &out.PodQpsQuota
		*out = make([]PodQpsQuotaSpec, len(*in))
		copy(*out, *in)
	}
	if in.PodQpsReal != nil {
		in, out := &in.PodQpsReal, &out.PodQpsReal
		*out = make([]PodQpsQuotaRealSpec, len(*in))
		copy(*out, *in)
	}
	if in.ChildClusterState != nil {
		in, out := &in.ChildClusterState, &out.ChildClusterState
		*out = make([]ChildClusterState, len(*in))
		copy(*out, *in)
	}
	if in.PodQpsIncreaseOrDecrease != nil {
		in, out := &in.PodQpsIncreaseOrDecrease, &out.PodQpsIncreaseOrDecrease
		*out = make([]PodQpsIncreaseOrDecreaseSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSpec.
func (in *QuotaSpec) DeepCopy() *QuotaSpec {
	if in == nil {
		return nil
	}
	out := new(QuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaStatus) DeepCopyInto(out *QuotaStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaStatus.
func (in *QuotaStatus) DeepCopy() *QuotaStatus {
	if in == nil {
		return nil
	}
	out := new(QuotaStatus)
	in.DeepCopyInto(out)
	return out
}
