apiVersion: v1
kind: ConfigMap
metadata:
  name: quota-conf
  namespace: {{ .Values.namespace }}
  labels:
    app: quota
    component: quota-conf
data:
  localClusterName: "{{ .Values.configmap.localClusterName }}"
  parentClusterName: "{{ .Values.configmap.parentClusterName }}"
  clusterLevel: "{{ .Values.configmap.clusterLevel }}"
  etcdEndpoint: "{{ .Values.configmap.etcdEndpoint }}"
  qpsQuotaUrl: "{{ .Values.configmap.qpsQuotaUrl }}"
  qpsRegisterUrl: "{{ .Values.configmap.qpsRegisterUrl }}"
  sidRegisterUrl: "{{ .Values.configmap.sidRegisterUrl }}"
  sidRegisterDelUrl: "{{ .Values.configmap.sidRegisterDelUrl }}"
  kubeconfig: |
{{ .Files.Get "kubeconfig.json" | indent 4 }}
  kubeParentconfig: |
{{ .Files.Get "kubeParentconfig.json" | indent 4 }}
