{{- if .Values.crds.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: quotas.cluster.pml.com.cn
spec:
  group: cluster.pml.com.cn
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                supervisorName:
                  type: string
                myAreaName:
                  type: string
                nodeAreaType:
                  type: string
  names:
    kind: quota
    plural: quotas
  scope: Namespaced
{{- end }}
