apiVersion: serverless.pml.com.cn/v1
kind: Serverless
metadata:
  annotations:
  finalizers:
  - serverless.hpa.finalizers.pml.com.cn
  labels:
    apps.gaia.io/component: sample-s2-4
    apps.gaia.io/description: default-8677-20230413111950-12-2023042705
  name: sample-s2-4
  namespace: default
spec:
  module:
    metadata:
      labels:
        apps.gaia.io/component: sample-s2-4
        apps.gaia.io/description: default-8677-20230413111950-12-2023042705
    spec:
      containers:
      - env:
        - name: SCNNUM
          value: "1"
        - name: SCNID4
          value: /inner-private/celeven/case11component4/1
        image: nginx
        name: case11component4
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      hostNetwork: true
      nodeSelector:
        hypernode.cluster.pml.com.cn/node-role: Public
        hypernode.cluster.pml.com.cn/runtime-state: kata
  name: sample-s2-4
  namespace: default
  runtimeType: kata
  workload:
    traitServerless:
      foundingmember: true
      maxQPS: 10000
      qpsStep: 10
      threshold: '{"qpsMax":10,"cpuMin":0,"cpuMax":100,"qpsMin":4,"memMax":100,"memMin":0}'
    workloadtype: serverless
