# permissions for end users to view serverlesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serverless-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: serverless
    app.kubernetes.io/part-of: serverless
    app.kubernetes.io/managed-by: kustomize
  name: serverless-viewer-role
rules:
- apiGroups:
  - serverless.pml.com.cn
  resources:
  - serverlesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serverless.pml.com.cn
  resources:
  - serverlesses/status
  verbs:
  - get
