apiVersion: serverless.pml.com.cn/v1
kind: Serverless
metadata:
  labels:
    app.kubernetes.io/name: serverless
    app.kubernetes.io/instance: serverless-sample
    app.kubernetes.io/part-of: serverless
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: serverless
  name: serverless-sample
spec:
  # TODO(user): Add fields here
